#Especificar requerimientos del contenedor 

#importamos la imagen 
FROM python:3.12-slim 

#Creamos carpeta de trabajo del contenerdor
WORKDIR /app

#Copiamos los requerimientos del servidor 
COPY requirements.txt .

#Instalamos los requerimientos 
RUN pip install --no-cache-dir -r requirements.txt

#Copiar el codigo de nuestra API
COPY ./app ./app

#Exponer el puerto 
EXPOSE 5000

#Comando de ejecucion FASTAPI
CMD ["uvicorn","app.main:app","--host","0.0.0.0","--port","5000","--reload"]

